### ISSUE TITLE
Allow to customize shell level setting

### ISSUE THREAD

**Issue by weirdgiraffe** [zimfw/asciiship#1]
I'm a tmux user. So my terminal session normally looks like `tmux` and then everything else.

I would like to have the ability to customise (set via env or so) the minimal value of shell level which will be shown in the prompt. Because tmux is the second level already, I see this annoying `(2)` in my shell prompt all the time.  So it would be great to have an option to adjust the minimal shell level somehow like `ZSH_ASCIISHIP_MIN_SHELL_LEVEL=3`.  Or even better, because I'm using ranger where I can also open shells,  to just provide the ability to set some adjustment like  `ZSH_ASCIISHIP_SHELL_ADJUSTMENT=-1`. That will hide tmux and will provide info about further sessions. 

Alternatively, if it's possible to detect that tmux is running right now, it would be great to increase this minimal shell layer to 3 to allow tmux to run without affecting the prompt. env var like `ZSH_ASCIISHIP_TMUX_ADJUSTMENT=true`

**Comment by weirdgiraffe** [comment]
I'll just fork the repo an customize it for myself. I make no sense to complicate the theme

**Comment by ericbn** [comment]
Cool, that's one of the ideas with our themes: to serve as a starting point for you to customize your own.
