### ISSUE TITLE
Visual aid to determine the current keymap with Vi keybindings

### ISSUE THREAD

**Issue by antoineco** [zimfw/asciiship#2]
_First of all, excellent job with the prompt 👏  I discovered today that Zim had a "new" default prompt after reinstalling my machine, and it is so simple and functional that I want to use it instead of Pure._

**Is your feature request related to a problem? Please describe.** 

When Vi keybindings are enabled (`bindkey -v`) there is no visual aid to determine whether zle's current keymap is `viins` (insert mode, default) or `vicmd` (command mode, when pressing ESC).

I think making such visual aid part of the prompt would be sensible because:
1. Vi keybindings are [built into Zsh](https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html)
2. The keymap configuration is [part of Zim's default configuration](https://github.com/zimfw/install/blob/c012ced0f2779db6e1a7f7494e2596f24e14be59/install.zsh#L223-L224)

**Describe the solution you'd like**  

- **Option 1** (preferred)

   Change the prompt symbol to another character of the ASCII table while the `vicmd` keymap is active. There aren't that many but, as an example, the _extended_ ASCII table contains `§` (char 167), which should be available in any font and is quite subtle.

   It looks like below (_viins / vicmd_):

   ![image](https://user-images.githubusercontent.com/3299086/182198851-86c2de44-845c-45c1-8695-0bbe6b5cd407.png)
   ![image](https://user-images.githubusercontent.com/3299086/182199251-cce5f799-5a5f-48fe-b673-1baa815742dd.png)

- **Option 2**

   Change the color of the prompt symbol to something other than green or red while the `vicmd` keymap is active. I suggest `cyan` because it is somewhat close to green, yet distinguishable.

   Potential issue: the `red` color coding — which indicates that the previous command failed — is lost while in `vicmd` mode, unless translated to yet another color like magenta. I'm not yet sure how I'd feel about that.

   It looks like below (_viins / vicmd_):

   ![image](https://user-images.githubusercontent.com/3299086/182198851-86c2de44-845c-45c1-8695-0bbe6b5cd407.png)
   ![image](https://user-images.githubusercontent.com/3299086/182198975-0ecfa345-5eb8-4e83-92aa-c1ce555d3908.png)

**Describe alternatives you've considered**

Spaceship includes a [text indicator](https://spaceship-prompt.sh/options/#vi-mode-vi_mode) (`[I]` / `[N]`) on the first line, which I find bloated.

Starship allows configuring the [shape and color of the prompt symbol](https://starship.rs/config/#character) in different states, which I find interesting and well designed. But considering the minimal nature of asciiship, I think a sane default that people can customize by forking the prompt's code would be enough.

Changing the terminal's cursor shape while changing mode e.g. from beam to block and back — like in Vim itself — would be controversial and error prone.

**Additional context**

\-

**Comment by ericbn** [comment]
Hi @antoineco. So good to know you like our lightweight prompt theme!  :- D

Not sure which indicator to pick for the vicmd keymap. We're already using `#` when root, `%` otherwise. I'd rather keep just the lower ASCII chars for this prompt. Also, it's already green or red depending on the exit status of the last command. I agree changing the terminal cursor shape is controversial and error prone.

If you want to experiment with it yourself, we have two themes that have vicmd keymap indicators implemented:
* [sorin](https://github.com/zimfw/sorin/blob/a46a94119339fd9512d40deeee49b01a7a51bd84/sorin.zsh-theme#L31-L47)
* [s1ck94](https://github.com/zimfw/s1ck94/blob/cf2d69211764569573a883a32ebf8810e28e6fb4/s1ck94.zsh-theme#L9-L26)

It's quite a good amount of additional code.

**Comment by ericbn** [comment]
This is what I've come up with: changing the prompt indicator to standout when in vicmd.

```diff
diff --git a/asciiship.zsh-theme b/asciiship.zsh-theme
index def650b..7641305 100644
--- a/asciiship.zsh-theme
+++ b/asciiship.zsh-theme
@@ -1,5 +1,23 @@
 # vim:et sts=2 sw=2 ft=zsh

+_prompt_asciiship_vimode() {
+  case ${KEYMAP} in
+    vicmd) print -n '%S%#%s' ;;
+    *) print -n '%#' ;;
+  esac
+}
+
+_prompt_asciiship_keymap_select() {
+  zle reset-prompt
+  zle -R
+}
+if autoload -Uz is-at-least && is-at-least 5.3; then
+  autoload -Uz add-zle-hook-widget && \
+      add-zle-hook-widget -Uz keymap-select _prompt_asciiship_keymap_select
+else
+  zle -N zle-keymap-select _prompt_asciiship_keymap_select
+fi
+
 typeset -g VIRTUAL_ENV_DISABLE_PROMPT=1

 setopt nopromptbang prompt{cr,percent,sp,subst}
@@ -31,5 +49,5 @@ fi

 PS1='
 %(2L.%B%F{yellow}(%L)%f%b .)%(!.%B%F{red}%n%f%b in .${SSH_TTY:+"%B%F{yellow}%n%f%b in "})${SSH_TTY:+"%B%F{green}%m%f%b in "}%B%F{cyan}%~%f%b${(e)git_info[prompt]}${VIRTUAL_ENV:+" via %B%F{yellow}${VIRTUAL_ENV:t}%b%f"}${duration_info}
-%B%(1j.%F{blue}*%f .)%(?.%F{green}.%F{red}%? )%#%f%b '
+%B%(1j.%F{blue}*%f .)%(?.%F{green}.%F{red}%? )$(_prompt_asciiship_vimode)%f%b '
 unset RPS1
```

**Comment by antoineco** [comment]
I hadn't though about standout, that could be a good approach I think! Underline comes to mind too.

I know that the `screen-*` / `tmux-*` terminfos that ship with macOS ~don't include italics and standout~, but

- those are much less common than `xterm-*`
- a lot of macOS users who rely on these capabilities either enable them manually or recompile their terminfo from a more recent ncurses to enable them 

I'll try your patch today and report here.
Thanks for looking into this so quickly!

**Comment by antoineco** [comment]
Contrary to what I remembered, _standout_ does work perfectly fine in tmux on macOS, with the default tmux config (`TERM=screen-256color`) and the OS' default terminfo.
It also works in various terminal emulators I've tried on macOS, with various xterm terminfo variants.

_tmux 3.3, screen-256color_

<img width="338" alt="image" src="https://user-images.githubusercontent.com/3299086/182310272-fcb16c46-fe8d-4b2c-bb60-5e1970f66459.png">

_Terminal.app, xterm-256color_

<img width="320" alt="image" src="https://user-images.githubusercontent.com/3299086/182310656-366896bb-45fc-455c-913e-7a7134cb3b21.png">

_Kitty, xterm-kitty_

<img width="312" alt="image" src="https://user-images.githubusercontent.com/3299086/182310781-9e79243d-21a5-4c20-9b05-62049d78f0ce.png">

---

Patch applied, I think it looks great:

<img width="211" alt="image" src="https://user-images.githubusercontent.com/3299086/182312007-0c1381b7-9de9-444b-b1e7-aa05eb19ecc6.png">

<img width="204" alt="image" src="https://user-images.githubusercontent.com/3299086/182311811-f0ae5591-29d4-4eb3-b706-4738099ef116.png">

---

Underline wouldn't be very clear (and is probably not as widely supported as standout):

<img width="145" alt="image" src="https://user-images.githubusercontent.com/3299086/182312859-9902c711-b02f-470d-adbe-7f078ec86ef7.png">

<img width="195" alt="image" src="https://user-images.githubusercontent.com/3299086/182313112-6ba03879-e95d-4a28-9565-e6336dc536e5.png">
