### ISSUE TITLE
Setting to force display username and hostname

### ISSUE THREAD

**Issue by psztoch** [zimfw/asciiship#3]
For some environment hiding hostname is very dangerous. In example if you connect to virtual machine or container, hostname is hidden, and you might think you are on your home profile.

**Comment by ericbn** [comment]
Not sure how to detect we're in a virtual machine or container, so it would be automatic.

You can create your own fork of theme and customize it to your needs. To force showing the user and hostname:

```diff
-%(2L.%B%F{yellow}(%L)%f%b .)%(!.%B%F{red}%n%f%b in .${SSH_TTY:+"%B%F{yellow}%n%f%b in "})${SSH_TTY:+"%B%F{green}%m%f%b in "}%B%F{cyan}%~%f%b${(e)git_info[prompt]}${VIRTUAL_ENV:+" via %B%F{yellow}${VIRTUAL_ENV:t}%b%f"}${duration_info}
+%(2L.%B%F{yellow}(%L)%f%b .)%(!.%B%F{red}%n%f%b in .%B%F{yellow}%n%f%b in )%B%F{green}%m%f%b in %B%F{cyan}%~%f%b${(e)git_info[prompt]}${VIRTUAL_ENV:+" via %B%F{yellow}${VIRTUAL_ENV:t}%b%f"}${duration_info}

```

**Comment by ericbn** [comment]
Hi @psztoch. I see you created your fork https://github.com/psztoch/asciiship with your custom changes. Cool!  :- )

I'm going to close this.
