### ISSUE TITLE
Not showing complete git-info information

### ISSUE THREAD

**Issue by aanzolaavila** [zimfw/asciiship#4]
- [X] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [X] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [X] I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [X] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [X] I was able to reproduce the issue with a clean installation of Zim.
- [X] I've pasted the output of `zimfw info` below.

**Describe the bug**  
Ahead and behind indicators do not show in `asciiship` theme.

**Steps to reproduce**  
The fist 4 steps restart the shell with a clean installation of Zim in a temporary directory.
Use `exec zsh` when restarting the terminal or restarting the shell is needed.
1. `cd ${$(mktemp -d):A}`
2. `ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim exec zsh`
3. `curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh`
4. `exec zsh`
5. Other steps to reproduce the behavior

**Current behavior**  
The git-info plugins is only showing symbols for changes made (dirty), but does not show anything wrt to the remote (ahead or behind)
<img width="421" alt="image" src="https://github.com/zimfw/asciiship/assets/16315577/731fe4aa-27f4-4eab-98f1-a00c897d31fb">

**Expected behavior**  
It should show the symbols as expected from the pages example.
![image](https://github.com/zimfw/asciiship/assets/16315577/ef40ecc5-e9df-4b7d-b204-a1e590903f99)

**zimfw info**  
```
zimfw version:        1.11.3 (built at 2023-02-26 00:43:41 UTC, previous commit is 6a24459)
OSTYPE:               darwin22.0
TERM:                 xterm-256color
TERM_PROGRAM:         tmux
TERM_PROGRAM_VERSION: 3.3a
ZIM_HOME:             /Users/aanzolaavila/.cache/zim
ZSH_VERSION:          5.9
```

**Additional context**  
I've setup the `  zstyle ':zim:git-info' verbose yes` option, but nothing changes, I've also set up every individual option with a format value, but does not take effect on the ahead or behind indicators.

**Comment by aanzolaavila** [comment]
If it helps, this is where I set the configuration in my files: https://github.com/aanzolaavila/.zsh/blob/main/zim.zsh#L4
And this is my zimfw config file: https://github.com/aanzolaavila/dotfiles/blob/main/home/dot_zimrc

**Comment by ericbn** [comment]
Thanks for reporting this. It was a regression I introduced in the git-info module. It's fixed now. Please run `zimfw update`.
